// current player constants
export const CURRENT_PLAYER_CHARACTER_SELECT = "CURRENT_PLAYER_CHARACTER_SELECT"
export const CURRENT_PLAYER_POINT_INCREASE = "CURRENT_PLAYER_POINT_INCREASE"
export const GENERATE_NEW_WORD_ON_SUCCESS = "GENERATE_NEW_WORD_ON_SUCCESS"

// opponent player constants
export const OPPONENT_PLAYER_CHARACTER_SELECT =
  "OPPONENT_PLAYER_CHARACTER_SELECT"
export const OPPONENT_PLAYER_POINT_INCREASE = "OPPONENT_PLAYER_POINT_INCREASE"
export const OPPONENT_PLAYER_POINT_INCREASE_MULTIPLAYER =
  "OPPONENT_PLAYER_POINT_INCREASE_MULTIPLAYER"
export const SET_OPPONENT_DIFFICULTY_LEVEL = "SET_OPPONENT_DIFFICULTY_LEVEL"

export const GAME_START = "GAME_START"
export const GAME_END = "END_GAME"

export const SET_GAME_TYPE = "SET_GAME_TYPE"

export const RESET_CURRENT_PLAYER_INFO = "RESET_CURRENT_PLAYER_INFO"
export const RESET_OPPONENT_PLAYER_INFO = "RESET_OPPONENT_PLAYER_INFO"
export const RESET_GAME_STATE = "RESET_GAME_STATE"

export const TOGGLE_VIRTUAL_KEYBOARD = "TOGGLE_VIRTUAL_KEYBOARD"
export const TOTAL_WORDS_TYPED_INCREASE = "TOTAL_WORDS_TYPED_INCREASE"
export const FLUENT_WORDS_TYPED_INCREASE = "FLUENT_WORDS_TYPED_INCREASE"
export const ADD_WEAK_KEY_STROKE = "ADD_WEAK_KEY_STROKE"
export const START_TYPING_COUNTDOWN = "START_TYPING_COUNTDOWN"
export const INCREMENT_CHARACTER_TYPED = "INCREMENT_CHARACTER_TYPED"

// Multiplayer functions
export const SET_ROOM_NAME = "SET_ROOM_NAME"
export const SET_MY_SOCKET_ID = "SET_MY_SOCKET_ID"
export const SET_OPPONENT_SOCKET_ID = "SET_OPPONENT_SOCKET_ID"

// User Names
export const SET_CURRENT_PLAYER_NAME = "SET_CURRENT_PLAYER_NAME"
export const SET_OPPONENT_PLAYER_NAME = "SET_OPPONENT_PLAYER_NAME"
